---


- name: Set video routing
  connection: docker
  gather_facts: false
  hosts: all

  vars:
    video_routing_conf_path: /etc/nginx/video-routing.conf

  tasks:
    - name: Verify mapping is defined
      assert:
        that:
          - "streams_to_keys is defined"

    - name: Set video routing
      lineinfile:
        path: "{{ video_routing_conf_path }}"
        regexp: "(^\\s*pull\\s+rtmp://localhost/incoming)/\\S+(\\s.*\\bname={{ item.key | regex_escape() }}\\s.+;\\s*)$"
        line: "\\1/{{ item.value }}\\2"
        backrefs: yes
        backup: yes
      loop: "{{ streams_to_keys | from_json | dict2items }}"
      notify: Nginx reload config

    - name: Verify Nginx can read the new config
      command: nginx -t
      changed_when: False

  handlers:
    - name: Nginx reload config
      command: nginx -s reload
