---
# An Ansible playbook which modifies the assignment of RTMP streaming keys on the input
# to RTMP/HLS streams on the output, and restarts the Nginx container.

- name: Set video routing
  connection: docker
  gather_facts: false
  hosts: all

  vars:
    video_routing_conf_path: /etc/nginx/dynamic/video-routing.conf

  tasks:
    - name: Verify mapping is defined
      assert:
        that:
          - "streams_to_keys is defined"

    - name: Set video routing
      lineinfile:
        path: "{{ video_routing_conf_path }}"
        regexp: "(^\\s*pull\\s+rtmp://nginx-in/live)/\\S+(\\s.*\\bname={{ item.key | regex_escape() }}\\b.*;\\s*)$"
        line: "\\1/{{ item.value }}\\2"
        backrefs: yes
        backup: yes
      loop: "{{ streams_to_keys | from_json | dict2items }}"
      notify: Nginx reload config

    - name: Verify Nginx can read the new config
      command: nginx -t
      changed_when: False

  handlers:
    - name: Nginx reload config
    # We use the docker command here to restart rather than the docker
    # module, to work around an issue where using the module from
    # within a container to restart another container causes it to
    # stop and not restart.
      command: docker restart "{{ inventory_hostname }}"
      delegate_to: localhost
